apiVersion: v1
kind: ConfigMap
metadata:
  name: avi-grafana-configmap
  namespace: avi-metrics
data:
  datasource.yml: |
     apiVersion: 1
     datasources:
     - name: graphite
       type: graphite
       orgId: 1
       url: http://graphite:8008
       jsonData:
          graphiteVersion: "1.13"
          tlsAuth: false
          tlsAuthWithCACert: false
       version: 1
       editable: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: avi-metrics
  name: avi-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avi-grafana
  template:
    metadata:
      labels:
        app: avi-grafana
    spec:
      volumes:
        - name: datasource-config-volume
          configMap:
            name: avi-grafana-configmap
            items:
            - key: datasource.yml
              path: datasource.yml
      containers:
        - name: avi-grafana
          image: avinetworks/grafana:latest
          ports:
            - containerPort: 3000
              name: port-3000
          volumeMounts:
          - name: datasource-config-volume
            mountPath: /etc/grafana/provisioning/datasources/datasource.yml
            subPath: datasource.yml
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: avi-metrics
spec:
  ports:
   - name: port-3000
     protocol: TCP
     targetPort: 3000
     port: 3000
  selector:
     app: avi-grafana
  type: LoadBalancer
